### ISSUE TITLE
Documentation: missing nightly disclaimer for immutable and simd features

### ISSUE THREAD

**Issue by ozwaldorf** [sdd-org/kiddo#115]
As the title says, the crate is unable to be built with the stable toolchain when using the `immutable` or `simd` features. To make this readily apparent, a disclaimer should be added to the crate documentation

**Comment by sdd** [comment]
Sure, will do. This was the reason that I gated `immutable` (and one of the reasons for `simd`) behind crate features, so that the rest of the library would be available to use on stable. 

In fact I think that immutable could now be made available without requiring nightly . The only use of unstable Rust is where I use the global allocator but I could make the feature more specific to that global-allocator code rather than gating off the entirity of the `ImmutableTree`. It should be a quick change, I'll look into it over the weekend!

**Comment by sdd** [comment]
I've just merged https://github.com/sdd/kiddo/pull/120 which lets `ImmutableKdTree` work on stable. Additionally I've updated the docs to make it clear which crate features don't work on stable.

I'll release these changes today or tomorrow - I'm going to try to address a few more issues at the same time.
