### ISSUE TITLE
Unsupported architecture: wasm32-unknown-unknown in v.3

### ISSUE THREAD

**Issue by lagleki** [sdd-org/kiddo#116]
wasm no longer supported?

**Comment by sdd** [comment]
Apologies, this was accidental, and probably due to the SIMD code not taking into account architectures other than x86-64 and ARM. I will fix as soon as I can, and any PRs to fix this before I do are welcome.

**Comment by sdd** [comment]
Hi @lagleki,

Now that I've looked into it, I don't think the issue is due to the SIMD code. Can you share a minimal WASM example that worked with an older version of Kiddo, but doesn't work now? It will help me fix it, and I can then add the example to the project and build it in CI to ensure that I don't break WASM compilation in future.

Thanks!

**Comment by lagleki** [comment]
@sdd can you please check? https://github.com/lagleki/kiddo-test

**Comment by sdd** [comment]
Thanks for that! Your test case made it easy for me to find the problem. I've got a fix incoming on https://github.com/sdd/kiddo/pull/125.

**Comment by sdd** [comment]
Fix released as part of [v4.0.0](https://crates.io/crates/kiddo/4.0.0) release
