### ISSUE TITLE
Associated Data in ImmutableKdTree

### ISSUE THREAD

**Issue by earthnuker** [sdd-org/kiddo#187]
Hello,

I'm interested in testing this library to see how it compares to rstar for my use-case, especially the ImmutableKdTree. However my use-case requires some metadata to be stored inside each node of the tree, however it looks like currently ImmutableKdTree only stored an incrementing ID for each node (https://github.com/sdd/kiddo/blob/master/src/immutable/float/kdtree.rs#L216), which would work for my use case, i could store the associated data in a separate array and index into that, however since the regular (mutable) KdTree can store associated data for each node, i was wondering if there was a reason the immutable one does not possess this ability.

Best regard,
Daniel

**Comment by sdd** [comment]
Hi Daniel,

I switched away from allowing associated data to be stored for each node as it increased the size of the leaf nodes in memory, and since queries in kiddo are essentially limited by how much of the tree can fit into L2/L3 cache and by how quickly leaf nodes can be retrieved from main memory, storing associated data in the leaves was a performance anti-pattern that I wanted to steer users away from. The ImmutableTree's design principles are to optimise for performance as much as is possible.

You've hit on the recommended solution which is to store a separate Vec of structs containing your associated data and to store the index of each item alongside it's point inside the k-d tree.
